DROP TABLE IF EXISTS cards;
CREATE TABLE cards AS
SELECT
    json_extract(json, '$.object') AS object_type,
    json_extract(json, '$.id') AS card_id,
    json_extract(json, '$.oracle_id') AS oracle_id,
    json_extract(json, '$.name') AS name,
    json_extract(json, '$.lang') AS lang,
    json_extract(json, '$.released_at') AS released_at,
    json_extract(json, '$.uri') AS uri,
    json_extract(json, '$.scryfall_uri') AS scryfall_uri,
    json_extract(json, '$.layout') AS layout,
    json_extract(json, '$.highres_image') AS highres_image,
    json_extract(json, '$.mana_cost') AS mana_cost,
    json_extract(json, '$.cmc') AS cmc,
    json_extract(json, '$.type_line') AS type_line,
    json_extract(json, '$.oracle_text') AS oracle_text,
    json_extract(json, '$.power') AS power,
    json_extract(json, '$.toughness') AS toughness,
    json_extract(json, '$.colors') AS colors,
    json_extract(json, '$.color_identity') AS color_identity,
    json_extract(json, '$.keywords') AS keywords,
    json_extract(json, '$.reserved') AS reserved,
    json_extract(json, '$.game_changer') AS game_changer,
    json_extract(json, '$.foil') AS foil,
    json_extract(json, '$.nonfoil') AS nonfoil,
    json_extract(json, '$.oversized') AS oversized,
    json_extract(json, '$.promo') AS promo,
    json_extract(json, '$.reprint') AS reprint,
    json_extract(json, '$.variation') AS variation,
    json_extract(json, '$.set_id') AS set_id,
    json_extract(json, '$.set') AS set_code,
    json_extract(json, '$.set_name') AS set_name,
    json_extract(json, '$.set_type') AS set_type,
    json_extract(json, '$.collector_number') AS collector_number,
    json_extract(json, '$.rarity') AS rarity,
    json_extract(json, '$.flavor_text') AS flavor_text,
    json_extract(json, '$.artist') AS artist,
    json_extract(json, '$.illustration_id') AS illustration_id,
    json_extract(json, '$.border_color') AS border_color,
    json_extract(json, '$.frame') AS frame,
    json_extract(json, '$.security_stamp') AS security_stamp,
    json_extract(json, '$.full_art') AS full_art,
    json_extract(json, '$.textless') AS textless,
    json_extract(json, '$.booster') AS booster,
    json_extract(json, '$.story_spotlight') AS story_spotlight,
    json_extract(json, '$.edhrec_rank') AS edhrec_rank,
    json_extract(json, '$.penny_rank') AS penny_rank,


    json_extract(json, '$.image_uris.small') AS image_small,
    json_extract(json, '$.image_uris.normal') AS image_normal,
    json_extract(json, '$.image_uris.large') AS image_large,
    json_extract(json, '$.image_uris.png') AS image_png,
    json_extract(json, '$.image_uris.art_crop') AS image_art_crop,
    json_extract(json, '$.image_uris.border_crop') AS image_border_crop,

    json_extract(json, '$.prices.usd') AS price_usd,
    json_extract(json, '$.prices.eur') AS price_eur,
    json_extract(json, '$.prices.tix') AS price_tix,

    json_extract(json, '$.legalities.standard') AS legal_standard,
    json_extract(json, '$.legalities.modern') AS legal_modern,
    json_extract(json, '$.legalities.commander') AS legal_commander,

    json_extract(json, '$.related_uris.gatherer') AS uri_gatherer,
    json_extract(json, '$.related_uris.edhrec') AS uri_edhrec,
    json_extract(json, '$.purchase_uris.tcgplayer') AS purchase_tcgplayer,
    json_extract(json, '$.purchase_uris.cardmarket') AS purchase_cardmarket

FROM cards_raw;