-- Active: 1756438169117@@127.0.0.1@3306
SELECT
    json -> 'object' AS object_type,
    json -> 'id' AS card_id,
    json -> 'oracle_id' AS oracle_id,
    json -> 'name' AS name,
    json -> 'lang' AS lang,
    json -> 'released_at' AS released_at,
    json -> 'uri' AS uri,
    json -> 'scryfall_uri' AS scryfall_uri,
    json -> 'layout' AS layout,
    json -> 'highres_image' AS highres_image,
    json -> 'mana_cost' AS mana_cost,
    json -> 'cmc' AS cmc,
    json -> 'type_line' AS type_line,
    json -> 'oracle_text' AS oracle_text,
    json -> 'power' AS power,
    json -> 'toughness' AS toughness,
    json -> 'colors' AS colors,
    json -> 'color_identity' AS color_identity,
    json -> 'keywords' AS keywords,
    json -> 'reserved' AS reserved,
    json -> 'game_changer' AS game_changer,
    json -> 'foil' AS foil,
    json -> 'nonfoil' AS nonfoil,
    json -> 'oversized' AS oversized,
    json -> 'promo' AS promo,
    json -> 'reprint' AS reprint,
    json -> 'variation' AS variation,
    json -> 'set_id' AS set_id,
    json -> 'set' AS set_code,
    json -> 'set_name' AS set_name,
    json -> 'set_type' AS set_type,
    json -> 'collector_number' AS collector_number,
    json -> 'rarity' AS rarity,
    json -> 'flavor_text' AS flavor_text,
    json -> 'artist' AS artist,
    json -> 'illustration_id' AS illustration_id,
    json -> 'border_color' AS border_color,
    json -> 'frame' AS frame,
    json -> 'security_stamp' AS security_stamp,
    json -> 'full_art' AS full_art,
    json -> 'textless' AS textless,
    json -> 'booster' AS booster,
    json -> 'story_spotlight' AS story_spotlight,
    json -> 'edhrec_rank' AS edhrec_rank,
    json -> 'penny_rank' AS penny_rank,

    -- Nested JSON objects
    json -> 'image_uris' -> 'small' AS image_small,
    json -> 'image_uris' -> 'normal' AS image_normal,
    json -> 'image_uris' -> 'large' AS image_large,
    json -> 'image_uris' -> 'png' AS image_png,
    json -> 'image_uris' -> 'art_crop' AS image_art_crop,
    json -> 'image_uris' -> 'border_crop' AS image_border_crop,

    json -> 'prices' -> 'usd' AS price_usd,
    json -> 'prices' -> 'eur' AS price_eur,
    json -> 'prices' -> 'tix' AS price_tix,

    json -> 'legalities' -> 'standard' AS legal_standard,
    json -> 'legalities' -> 'modern' AS legal_modern,
    json -> 'legalities' -> 'commander' AS legal_commander,

    json -> 'related_uris' -> 'gatherer' AS uri_gatherer,
    json -> 'related_uris' -> 'edhrec' AS uri_edhrec,
    json -> 'purchase_uris' -> 'tcgplayer' AS purchase_tcgplayer,
    json -> 'purchase_uris' -> 'cardmarket' AS purchase_cardmarket

FROM cards_raw;